#pragma once

#include <chrono>
#include <ctime>
#include <iostream>
#include <string>
#include <sstream>

typedef std::chrono::high_resolution_clock Clock;
typedef std::chrono::system_clock SClock;

/**
 * \brief Converts timestamp to time of day (UTC timezone) and prints to console, accurate to nanosecond level
 * \param prefix String identifier printed alongside time of day
 * \param now time_point datatype generated by a system_clock
 * \param ik Integer identifier printed alongside time of day
*/
void print_nanoseconds(std::string prefix, std::chrono::time_point<std::chrono::system_clock> now, int ik);

/**
 * \brief Logs to a given stringstream object instead of printing to console
*/
void print_nanoseconds(std::string prefix, std::chrono::time_point<std::chrono::system_clock> now, int ik, std::stringstream &ss);